name: Build XenoSOTimer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish macOS app
        run: |
          dotnet publish -c Release -r osx-arm64 --self-contained true -p:UseAppHost=true
          cd bin/Release/net8.0/osx-arm64/publish
          zip -r XenoSOTimer_Mac_${{ github.ref_name }}.zip XenoSOTimer.app
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: XenoSOTimer-Mac
          path: bin/Release/net8.0/osx-arm64/publish/XenoSOTimer_Mac_${{ github.ref_name }}.zip
